version: '3.7'

networks:
  kafka-net:
    name: kafka-net
    driver: bridge

services:
  zookeeper:
    image: zookeeper:3.6.1
    container_name: zookeeper
    restart: unless-stopped
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    volumes:
      - C:/Kanishk/learning/spring-kafka/docker-volumes-fake/zookeeper-data:/data
      - C:/Kanishk/learning/spring-kafka/docker-volumes-fake/zookeeper-catalog-data:/datalog
      - C:/Kanishk/learning/spring-kafka/docker-volumes-fake/zookeeper-logs:/logs

  kafka1:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka1
    restart: unless-stopped
    networks:
      - kafka-net
    ports:
      - '9092:9092'
    volumes:
       - C:/Kanishk/learning/spring-kafka/docker-volumes-fake/kafka-data1/bitnami/kafka.docker.sock:/var/run/docker.sock
       - C:/Kanishk/learning/spring-kafka/docker-volumes-fake/kafka-data1/bitnami/kafka:/kafka
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    depends_on:
      - zookeeper
      
  kafka2:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka2
    restart: unless-stopped
    networks:
      - kafka-net
    ports:
      - '9093:9093'
    volumes:
       - C:/Kanishk/learning/spring-kafka/docker-volumes-fake/kafka-data2/bitnami/kafka.docker.sock:/var/run/docker.sock
       - C:/Kanishk/learning/spring-kafka/docker-volumes-fake/kafka-data2/bitnami/kafka:/kafka
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:29093,PLAINTEXT_HOST://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29093,PLAINTEXT_HOST://${DOCKER_HOST_IP:-127.0.0.1}:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    depends_on:
      - zookeeper 

  kafka3:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka3
    restart: unless-stopped
    networks:
      - kafka-net
    ports:
      - '9094:9094'
    volumes:
       - C:/Kanishk/learning/spring-kafka/docker-volumes-fake/kafka-data3/bitnami/kafka.docker.sock:/var/run/docker.sock
       - C:/Kanishk/learning/spring-kafka/docker-volumes-fake/kafka-data3/bitnami/kafka:/kafka
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:29094,PLAINTEXT_HOST://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:29094,PLAINTEXT_HOST://${DOCKER_HOST_IP:-127.0.0.1}:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    depends_on:
      - zookeeper       