package com.learning.kafka.entities;

import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@Data
@Entity
//default table name would be Book in h2, book in mysql
@Table(name = "books")
public class BookEntity {
	@Id
	//no need to auto generated by jpa, already event sender service handles this
	private String bookId;
	
	//columns name will be book_name
	@Column(nullable = false, length = 50)
	private String bookName;
	
	//column name will be book_author
	@Column(nullable = false, length = 50)
	private String bookAuthor;
	
	//extra proeprties auto generated by jpa
	@CreationTimestamp
	@Column(updatable = false)
	private LocalDateTime creationDate;
	
	@UpdateTimestamp
	private LocalDateTime lastModifiedDate;

	//no need to ser creationdate and lastmodifieddate, will be auto updated
	//book id is also not autogenerated by jpa
	public BookEntity(String bookId, String bookName, String bookAuthor) {
		this.bookId = bookId;
		this.bookName = bookName;
		this.bookAuthor = bookAuthor;
	}
	
	
}
